[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.11.12"
hooks = [
  { id = "ruff", args = ["--fix"] },
  { id = "ruff-format" },
]
